services:
  openproject:
    image: openproject/openproject:16
    container_name: openproject
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://openproject:${POSTGRES_PASSWORD}@db/openproject
      OPENPROJECT_HOST__NAME: ${OPENPROJECT_HOST__NAME}
      OPENPROJECT_HTTPS: "true"
      OPENPROJECT_SECRET_KEY_BASE: ${OPENPROJECT_SECRET_KEY_BASE}
      OPENPROJECT_DEFAULT__LANGUAGE: ${OPENPROJECT_DEFAULT__LANGUAGE}
      OPENPROJECT_USER__DEFAULT__THEME: ${OPENPROJECT_USER__DEFAULT__THEME}
      OPENPROJECT_SEED__ADMIN__USER__PASSWORD: ${OPENPROJECT_SEED__ADMIN__USER__PASSWORD}
      OPENPROJECT_SEED__ADMIN__USER__PASSWORD__RESET: ${OPENPROJECT_SEED__ADMIN__USER__PASSWORD__RESET}

      EMAIL_DELIVERY_METHOD: ${EMAIL_DELIVERY_METHOD}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USER_NAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASS}
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_ENABLE_STARTTLS_AUTO}

    ports:
      - "127.0.0.1:${HTTP_PORT}:80"
    volumes:
      - ./openproject_data:/var/openproject/assets

  db:
    image: postgres:17
    container_name: openproject_db
    restart: on-failure:2
    environment:
      POSTGRES_USER: openproject
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openproject
    volumes:
      - ./pgdata:/var/lib/postgresql/data
